apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "query-audit.fullname" . }}
  labels:
    {{- include "query-audit.labels" . | nindent 4 }}
data:
  AEVUM_LOG_LEVEL: "{{ .Values.config.AEVUM_LOG_LEVEL }}"
  AEVUM_HTTP_PORT: "{{ .Values.config.AEVUM_HTTP_PORT }}"
  AEVUM_ELASTICSEARCH_URL: "{{ .Values.config.AEVUM_ELASTICSEARCH_URL }}"
  AEVUM_EVENT_TIMELINE_URL: "{{ .Values.config.AEVUM_EVENT_TIMELINE_URL }}"
  AEVUM_DECISION_ENGINE_URL: "{{ .Values.config.AEVUM_DECISION_ENGINE_URL }}"
  AEVUM_OTEL_ENDPOINT: "{{ .Values.config.AEVUM_OTEL_ENDPOINT }}"

