apiVersion: v1
kind: Secret
metadata:
  name: {{ include "query-audit.fullname" . }}
  labels:
    {{- include "query-audit.labels" . | nindent 4 }}
type: Opaque
data:
  AEVUM_JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc }}
