apiVersion: v1
kind: Service
metadata:
  name: {{ include "query-audit.fullname" . }}
  labels:
    {{- include "query-audit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "query-audit.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

