{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "query-audit.fullname" . }}
  labels:
    {{- include "query-audit.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "query-audit.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /admin/metrics
{{- end }}
