services:
  mongodb:
    ports:
      - "27017:27017"

  dynamodb-local:
    ports:
      - "8000:8000"

  event-timeline:
    ports:
      - "8081:8080"
      - "9091:9090"
    environment:
      AEVUM_LOG_LEVEL: debug
    volumes:
      - ./services/event-timeline:/app

  decision-engine:
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./services/decision-engine:/src

  elasticsearch:
    ports:
      - "9200:9200"

  query-audit:
    ports:
      - "8082:8080"

  aevum-ui:
    ports:
      - "3000:80"
