version: "3.9"

services:
  mongodb:
    ports:
      - "27017:27017"

  dynamodb-local:
    ports:
      - "8000:8000"

  event-timeline:
    ports:
      - "8081:8080"
      - "9091:9090"
    environment:
      AEVUM_LOG_LEVEL: debug
    volumes:
      - ./services/event-timeline:/app

  decision-engine:
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./services/decision-engine:/src

  query-audit:
    environment:
      AEVUM_LOG_LEVEL: debug
    volumes:
      - ./services/query-audit:/app

  aevum-ui:
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: "1"
    volumes:
      - ./frontend/aevum-ui:/usr/share/nginx/html:ro
