apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aevum-ui.fullname" . }}
  labels:
    {{- include "aevum-ui.labels" . | nindent 4 }}
data:
  NGINX_ENTRYPOINT_QUIET_LOGS: "{{ .Values.config.NGINX_ENTRYPOINT_QUIET_LOGS }}"

