apiVersion: v1
kind: ConfigMap
metadata:
  name: aevum-config
  namespace: aevum-sit
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  MongoDB__DatabaseName: "decision_engine"
  EventTimeline__BaseUrl: "http://event-timeline:8080"
  AEVUM_LOG_LEVEL: "info"
  AEVUM_GIN_PORT: "8080"
  AEVUM_ECHO_PORT: "9090"
  AEVUM_DYNAMODB_TABLE: "aevum-events"
  AEVUM_AWS_REGION: "eu-central-1"
  AEVUM_OTEL_ENDPOINT: ""
  AEVUM_RATE_LIMIT_BURST: "100"
  AEVUM_RATE_LIMIT_RATE: "50"
