apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - dynamodb-local.yaml
  - dynamodb-init-job.yaml
  - decision-engine.yaml
  - event-timeline.yaml
