apiVersion: v1
kind: Secret
metadata:
  name: aevum-secrets
  namespace: aevum-sit
type: Opaque
stringData:
  MongoDB__ConnectionString: mongodb://mongodb:27017
  AEVUM_DYNAMODB_ENDPOINT: http://dynamodb-local:8000
  AEVUM_JWT_SECRET: change-me-in-sit
