apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-timeline.fullname" . }}
  labels:
    {{- include "event-timeline.labels" . | nindent 4 }}
type: Opaque
data:
  AEVUM_JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc }}
