{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "event-timeline.fullname" . }}
  labels:
    {{- include "event-timeline.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "event-timeline.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin
      interval: {{ .Values.serviceMonitor.interval }}
      path: /admin/metrics
{{- end }}
