apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-timeline.fullname" . }}
  labels:
    {{- include "event-timeline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "event-timeline.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.publicPort }}
      targetPort: http
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin

