apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-sit
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: aevum
spec:
  project: aevum
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 69.5.2
      helm:
        valueFiles:
          - $values/devops/monitoring/prometheus/prometheus-values.yaml
    - repoURL: https://github.com/kushal-sharma-works/aevum-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: aevum-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
