apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: query-audit-sit
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: aevum
spec:
  project: aevum
  source:
    repoURL: https://github.com/kushal-sharma-works/aevum-platform.git
    targetRevision: main
    path: devops/helm/charts/query-audit
    helm:
      valueFiles:
        - values.yaml
        - values-sit.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aevum-sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
