{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "decision-engine.fullname" . }}
  labels:
    {{- include "decision-engine.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "decision-engine.selectorLabels" . | nindent 6 }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              project: aevum
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - to:
        - namespaceSelector: {}
{{- end }}
