apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: aevum-dev
spec:
  limits:
    - defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: aevum-staging
spec:
  limits:
    - defaultRequest:
        cpu: 200m
        memory: 256Mi
      default:
        cpu: "1"
        memory: 1Gi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: aevum-prod
spec:
  limits:
    - defaultRequest:
        cpu: 500m
        memory: 512Mi
      default:
        cpu: "2"
        memory: 2Gi
      type: Container
