apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: aevum-sit
spec:
  limits:
    - defaultRequest:
        cpu: 200m
        memory: 256Mi
      default:
        cpu: "1"
        memory: 1Gi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: aevum-monitoring
spec:
  limits:
    - defaultRequest:
        cpu: 200m
        memory: 512Mi
      default:
        cpu: "1"
        memory: 2Gi
      type: Container
